/* 
 * File:   mcal_interrupt_gen_config.h
 * Author: zyadi
 *
 * Created on August 28, 2023, 12:35 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CONFIG_H
#define	MCAL_INTERRUPT_GEN_CONFIG_H

/*Section : Macro Declaration*/

#define FEATURE_ENALE   1
#define FEATURE_DISALE  0
#define INTERUPT_PRIORITY_LEVELS_ENABLE              FEATURE_ENALE 
#define EXTERNAL_INTERRUPT_INTX_FEATURE_ENABLE       FEATURE_ENALE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE   FEATURE_ENALE

#define ADC_INTERRUPT_FEATURE       FEATURE_ENALE
#define TIMER0_INTERRUPT_FEATURE    FEATURE_ENALE
#define TIMER1_INTERRUPT_FEATURE    FEATURE_ENALE
#define TIMER2_INTERRUPT_FEATURE    FEATURE_ENALE
#define TIMER3_INTERRUPT_FEATURE    FEATURE_ENALE
#define CCP1_INTERRUPT_FEATURE      FEATURE_ENALE
#define CCP2_INTERRUPT_FEATURE      FEATURE_ENALE


#endif	/* MCAL_INTERRUPT_GEN_CONFIG_H */

